[theme]
base            = "dark"
primaryColor    = "#3498DB"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1A1A2E"
textColor       = "#FAFAFA"
font            = "sans serif"

[server]
headless        = true
enableCORS      = false
